#!/usr/bin/env python2

import SimpleHTTPServer
import SocketServer
import os

PORT = 8080

root = os.path.dirname(os.path.realpath(__file__))
os.chdir(root)

print("Serving at http://localhost:", PORT)

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
httpd = SocketServer.TCPServer(("", PORT), Handler)
httpd.serve_forever()

